# coding: utf-8

"""
    Test FastAPI

    A test project for FastAPI

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_create_user(self) -> None:
        """Test case for create_user

        Create User
        """
        pass

    def test_get_users(self) -> None:
        """Test case for get_users

        Get Users
        """
        pass


if __name__ == '__main__':
    unittest.main()
