# coding: utf-8

"""
    Test FastAPI

    A test project for FastAPI

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.user_response_schema import UserResponseSchema

class TestUserResponseSchema(unittest.TestCase):
    """UserResponseSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserResponseSchema:
        """Test UserResponseSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserResponseSchema`
        """
        model = UserResponseSchema()
        if include_optional:
            return UserResponseSchema(
                name = '',
                email = '',
                id = 56,
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return UserResponseSchema(
                email = '',
                id = 56,
        )
        """

    def testUserResponseSchema(self):
        """Test UserResponseSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
